language: node_js
node_js:
 - "8"
script:
  - npm run test
branches:
  only:
    - master
before_deploy:
  - npm run build
deploy:
  provider: surge
  project: ./public/
  domain: another-ui-blog.surge.sh
  skip_cleanup: true
